version: '3.9'

services:
  postgressql:
    image: postgres
    restart: always
    ports: 
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: 35353
      POSTGRES_PORT: 5433
    volumes:
      - postgresData:/var/lib/postgresql/data
volumes:
  postgresData: